"""Static developer enablement catalog."""

from __future__ import annotations

from dataclasses import dataclass

SCHEMA_VERSION = "1.0"
TIMESTAMP = "2026-01-01T00:00:00Z"
AS_OF_DATE = "2026-01-01"
OUTPUT_DIR = "outputs/security/developer-enablement"
REPORT_DIR = "reports/security"
DOC_DIR = "docs/developer-security"


@dataclass(frozen=True)
class Guide:
    path: str
    title: str
    purpose: str


@dataclass(frozen=True)
class Command:
    command: str
    category: str
    purpose: str
    prerequisites: str
    expected_output: str
    modifies_tracked_evidence: bool


REQUIRED_GUIDES = [
    Guide("docs/developer-security/README.md", "Developer Security", "Guide index."),
    Guide(
        "docs/developer-security/secure-development-guide.md",
        "Secure Development Guide",
        "End-to-end lifecycle.",
    ),
    Guide(
        "docs/developer-security/getting-started-securely.md",
        "Getting Started Securely",
        "Local setup path.",
    ),
    Guide(
        "docs/developer-security/local-security-workflow.md",
        "Local Security Workflow",
        "Decision-oriented checks.",
    ),
    Guide(
        "docs/developer-security/pull-request-security-checklist.md",
        "Pull Request Security Checklist",
        "PR checklist.",
    ),
    Guide(
        "docs/developer-security/authentication-guide.md", "Authentication Guide", "JWT and roles."
    ),
    Guide(
        "docs/developer-security/authorisation-guide.md",
        "Authorisation Guide",
        "Permissions and roles.",
    ),
    Guide(
        "docs/developer-security/object-level-authorisation-guide.md",
        "Object-Level Authorisation Guide",
        "BOLA checks.",
    ),
    Guide(
        "docs/developer-security/secure-api-checklist.md",
        "Secure API Checklist",
        "Endpoint review.",
    ),
    Guide(
        "docs/developer-security/input-validation-guide.md",
        "Input Validation Guide",
        "Schema validation.",
    ),
    Guide(
        "docs/developer-security/logging-and-audit-guide.md",
        "Logging and Audit Guide",
        "Audit controls.",
    ),
    Guide(
        "docs/developer-security/secrets-management-guide.md",
        "Secrets Management Guide",
        "Secret handling.",
    ),
    Guide(
        "docs/developer-security/dependency-management-guide.md",
        "Dependency Management Guide",
        "Dependency changes.",
    ),
    Guide("docs/developer-security/sbom-guide.md", "SBOM Guide", "CycloneDX evidence."),
    Guide(
        "docs/developer-security/terraform-security-guide.md",
        "Terraform Security Guide",
        "IaC workflow.",
    ),
    Guide(
        "docs/developer-security/container-security-guide.md",
        "Container Security Guide",
        "Image hardening.",
    ),
    Guide(
        "docs/developer-security/ci-cd-security-guide.md",
        "CI/CD Security Guide",
        "Workflow controls.",
    ),
    Guide(
        "docs/developer-security/dynamic-testing-guide.md",
        "Dynamic Testing Guide",
        "Local DAST workflow.",
    ),
    Guide(
        "docs/developer-security/vulnerability-triage-guide.md",
        "Vulnerability Triage Guide",
        "Finding triage.",
    ),
    Guide(
        "docs/developer-security/remediation-verification-guide.md",
        "Remediation Verification Guide",
        "Closure workflow.",
    ),
    Guide(
        "docs/developer-security/security-exception-guide.md",
        "Security Exception Guide",
        "Exception governance.",
    ),
    Guide(
        "docs/developer-security/release-gate-guide.md", "Release Gate Guide", "Release decisions."
    ),
    Guide(
        "docs/developer-security/secure-code-review-guide.md",
        "Secure Code Review Guide",
        "Reviewer prompts.",
    ),
    Guide(
        "docs/developer-security/troubleshooting-security-tools.md",
        "Troubleshooting Security Tools",
        "Tool failures.",
    ),
    Guide("docs/developer-security/glossary.md", "Glossary", "Developer terms."),
    Guide(
        "docs/developer-security/onboarding-checklist.md",
        "Onboarding Checklist",
        "First contribution.",
    ),
]


COMMANDS = [
    Command(
        "make setup",
        "setup",
        "Create the virtual environment and install dependencies.",
        "Python 3.11+.",
        "Editable install succeeds.",
        False,
    ),
    Command(
        "make install",
        "setup",
        "Install dependencies into an existing virtual environment.",
        "Existing .venv.",
        "Editable install succeeds.",
        False,
    ),
    Command(
        "make run",
        "setup",
        "Start the local API on 127.0.0.1:8000.",
        "Installed app.",
        "Uvicorn starts locally.",
        False,
    ),
    Command(
        "make format",
        "quality",
        "Format code and apply safe Ruff fixes.",
        "Dev dependencies.",
        "Ruff completes.",
        False,
    ),
    Command(
        "make format-check",
        "quality",
        "Verify formatting.",
        "Dev dependencies.",
        "143 files already formatted.",
        False,
    ),
    Command(
        "make lint",
        "quality",
        "Run Ruff linting.",
        "Dev dependencies.",
        "All checks passed.",
        False,
    ),
    Command(
        "make type-check",
        "quality",
        "Run mypy on src and tests.",
        "Dev dependencies.",
        "Success: no issues found.",
        False,
    ),
    Command(
        "make test",
        "quality",
        "Run the full pytest suite.",
        "Dev dependencies.",
        "All tests pass.",
        False,
    ),
    Command(
        "make test-coverage",
        "quality",
        "Run tests with coverage threshold.",
        "Dev dependencies.",
        "Coverage is at least 85%.",
        False,
    ),
    Command(
        "make quality",
        "quality",
        "Run the main quality and evidence verifier chain.",
        "Dev dependencies; Terraform wrapper.",
        "Quality chain passes.",
        False,
    ),
    Command(
        "make dev-token-researcher",
        "authentication",
        "Generate a local researcher token.",
        "Local synthetic keys.",
        "A token is printed to stdout.",
        False,
    ),
    Command(
        "make dev-token-approver",
        "authentication",
        "Generate a local approver token.",
        "Local synthetic keys.",
        "A token is printed to stdout.",
        False,
    ),
    Command(
        "make dev-token-auditor",
        "authentication",
        "Generate a local auditor token.",
        "Local synthetic keys.",
        "A token is printed to stdout.",
        False,
    ),
    Command(
        "make auth-test",
        "API security",
        "Run targeted authentication tests.",
        "Dev dependencies.",
        "Selected auth tests pass.",
        False,
    ),
    Command(
        "make api-security-test",
        "API security",
        "Run API security tests.",
        "Dev dependencies.",
        "API security tests pass.",
        False,
    ),
    Command(
        "make api-security-evidence",
        "API security",
        "Generate API-security evidence.",
        "Existing tests/evidence inputs.",
        "API evidence files are written.",
        True,
    ),
    Command(
        "make verify-api-security-evidence",
        "API security",
        "Verify API-security evidence.",
        "Generated API evidence.",
        "Verifier exits 0.",
        False,
    ),
    Command(
        "make terraform-fmt-check",
        "Terraform",
        "Check Terraform formatting.",
        "Terraform wrapper.",
        "No formatting drift.",
        False,
    ),
    Command(
        "make terraform-init",
        "Terraform",
        "Initialise Terraform locally without deployment.",
        "Terraform CLI.",
        "Init completes.",
        False,
    ),
    Command(
        "make terraform-validate",
        "Terraform",
        "Validate Terraform configuration.",
        "Terraform CLI.",
        "Validation succeeds.",
        False,
    ),
    Command(
        "make terraform-test",
        "Terraform",
        "Run Terraform tests.",
        "Terraform CLI.",
        "Terraform tests pass.",
        False,
    ),
    Command(
        "make infrastructure-test",
        "Terraform",
        "Run local infrastructure policy tests.",
        "Dev dependencies.",
        "Infrastructure tests pass.",
        False,
    ),
    Command(
        "make checkov-scan",
        "AppSec",
        "Run Checkov IaC scan.",
        "Security dependencies.",
        "Scan summary has no failed checks.",
        True,
    ),
    Command(
        "make security-tools",
        "AppSec",
        "Print pinned scanner inventory.",
        "Security dependencies.",
        "Pinned versions are listed.",
        False,
    ),
    Command(
        "make secrets-scan",
        "AppSec",
        "Run Gitleaks via native binary or Docker fallback.",
        "Gitleaks or Docker.",
        "No leaks found.",
        True,
    ),
    Command(
        "make sast-semgrep",
        "AppSec",
        "Run Semgrep rules.",
        "Security dependencies.",
        "0 findings for current baseline.",
        True,
    ),
    Command(
        "make semgrep-test",
        "AppSec",
        "Run Semgrep rule tests.",
        "Security dependencies.",
        "Rule tests pass.",
        False,
    ),
    Command(
        "make sast-bandit",
        "AppSec",
        "Run Bandit.",
        "Security dependencies.",
        "No blocking findings.",
        True,
    ),
    Command(
        "make dependency-audit",
        "AppSec",
        "Run pip-audit.",
        "Security dependencies.",
        "No known vulnerabilities for current baseline.",
        True,
    ),
    Command(
        "make sbom",
        "AppSec",
        "Generate CycloneDX SBOM.",
        "Security dependencies.",
        "SBOM JSON is written.",
        True,
    ),
    Command(
        "make verify-sbom",
        "AppSec",
        "Validate SBOM structure.",
        "Generated SBOM.",
        "Validation exits 0.",
        False,
    ),
    Command(
        "make container-build-security",
        "container",
        "Build the local security image.",
        "Docker daemon.",
        "Image builds locally.",
        False,
    ),
    Command(
        "make container-scan",
        "container",
        "Run Trivy image scan.",
        "Trivy or Docker fallback.",
        "No blocking findings.",
        True,
    ),
    Command(
        "make appsec-fast",
        "AppSec",
        "Run fast AppSec checks.",
        "Gitleaks/Docker and security deps.",
        "Fast scans pass.",
        True,
    ),
    Command(
        "make appsec-full",
        "AppSec",
        "Run full AppSec aggregate.",
        "Docker daemon and security deps.",
        "AppSec evidence verifies.",
        True,
    ),
    Command(
        "make dynamic-fast",
        "dynamic security",
        "Run local dynamic pytest checks.",
        "Dev dependencies.",
        "8 dynamic tests pass.",
        True,
    ),
    Command(
        "make dynamic-full",
        "dynamic security",
        "Run local-only dynamic aggregate.",
        "Docker daemon and local bind.",
        "Dynamic evidence is refreshed.",
        True,
    ),
    Command(
        "make findings-full",
        "findings",
        "Normalise, enrich and verify findings.",
        "Source scanner outputs.",
        "Findings workflow completes.",
        True,
    ),
    Command(
        "make release-full",
        "release assurance",
        "Evaluate and report release gate.",
        "Findings evidence.",
        "Release workflow completes.",
        True,
    ),
    Command(
        "make lifecycle-full",
        "lifecycle",
        "Run vulnerability lifecycle workflow.",
        "Findings and release evidence.",
        "Lifecycle evidence verifies.",
        True,
    ),
    Command(
        "make evidence-full",
        "evidence",
        "Generate consolidated security evidence.",
        "All source evidence manifests.",
        "8 domains validate.",
        True,
    ),
    Command(
        "make security-assurance-full",
        "full assurance",
        "Run full local assurance chain.",
        "Dev dependencies and source evidence.",
        "Assurance chain passes.",
        True,
    ),
    Command(
        "make pre-commit-install",
        "setup",
        "Install pre-commit hooks.",
        "pre-commit package.",
        "Hooks installed.",
        False,
    ),
    Command(
        "make pre-commit-run",
        "quality",
        "Run pre-commit hooks over the repo.",
        "pre-commit package.",
        "Fast hooks pass.",
        False,
    ),
    Command(
        "make security-doctor",
        "developer enablement",
        "Check local prerequisite readiness.",
        "Python only.",
        "Readiness JSON is written.",
        True,
    ),
    Command(
        "make developer-docs-validate",
        "developer enablement",
        "Validate developer-security docs and references.",
        "Generated reports/evidence.",
        "Documentation validates.",
        False,
    ),
    Command(
        "make developer-enablement-evidence",
        "developer enablement",
        "Generate developer enablement evidence.",
        "Python only.",
        "Enablement evidence manifest is written.",
        True,
    ),
    Command(
        "make verify-developer-enablement-evidence",
        "developer enablement",
        "Verify developer enablement evidence.",
        "Generated enablement evidence.",
        "Verifier exits 0.",
        False,
    ),
    Command(
        "make developer-enablement-report",
        "developer enablement",
        "Generate developer enablement reports.",
        "Generated enablement evidence.",
        "Reports are written.",
        True,
    ),
    Command(
        "make developer-enablement-full",
        "developer enablement",
        "Run the full developer enablement workflow.",
        "Python only.",
        "Evidence, reports and docs validate.",
        True,
    ),
    Command(
        "make clean",
        "cleanup",
        "Remove local caches and build artifacts.",
        "None.",
        "Local caches are removed.",
        False,
    ),
]


CONTROL_MAPPINGS = [
    {
        "guidance_id": "DEV-GUIDE-SDLC",
        "guide": "docs/developer-security/secure-development-guide.md",
        "threat_ids": ["THR-REVIEW-001", "THR-SUPPLY-001"],
        "security_requirement_ids": ["SR-DEV-001", "SR-TM-001", "SR-FINDINGS-001"],
        "control_ids": ["SR-DEV-001", "SR-TM-001", "SR-FINDINGS-001"],
        "make_targets": [
            "quality",
            "appsec-full",
            "findings-full",
            "release-full",
            "lifecycle-full",
            "evidence-full",
        ],
        "tests": ["tests/security/test_developer_enablement.py"],
        "evidence_outputs": ["outputs/security/developer-enablement/enablement-summary.json"],
        "reports": ["reports/security/developer-security-workflow-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-PR",
        "guide": "docs/developer-security/pull-request-security-checklist.md",
        "threat_ids": ["THR-REVIEW-001"],
        "security_requirement_ids": ["SR-DEV-002", "SR-RELEASE-001"],
        "control_ids": ["SR-DEV-002", "SR-RELEASE-001"],
        "make_targets": ["quality", "appsec-fast", "release-full"],
        "tests": ["tests/security/test_developer_enablement.py"],
        "evidence_outputs": [
            "outputs/security/developer-enablement/pull-request-checklist-summary.json"
        ],
        "reports": ["reports/security/pull-request-security-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-AUTH",
        "guide": "docs/developer-security/authentication-guide.md",
        "threat_ids": ["THR-AUTH-001", "THR-AUTH-002"],
        "security_requirement_ids": ["SR-AUTH-001", "SR-DEV-003"],
        "control_ids": ["SR-AUTH-001", "SR-DEV-003"],
        "make_targets": ["auth-test", "api-security-test", "dynamic-fast"],
        "tests": [
            "tests/security/test_api_security_controls.py",
            "tests/dynamic/test_dynamic_api_security.py",
        ],
        "evidence_outputs": ["outputs/security/api-security/authentication-control-summary.json"],
        "reports": ["reports/security/authentication-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-AUTHZ",
        "guide": "docs/developer-security/authorisation-guide.md",
        "threat_ids": ["THR-AUTHZ-001", "THR-AUTHZ-002", "THR-AUTHZ-003"],
        "security_requirement_ids": ["SR-AUTHZ-001", "SR-AUTHZ-002", "SR-AUTHZ-003", "SR-DEV-003"],
        "control_ids": ["SR-AUTHZ-001", "SR-AUTHZ-002", "SR-AUTHZ-003"],
        "make_targets": ["api-security-test", "dynamic-full"],
        "tests": ["tests/security/test_api_security_controls.py"],
        "evidence_outputs": ["outputs/security/api-security/authorisation-matrix.json"],
        "reports": ["reports/security/authorisation-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-DEPENDENCY",
        "guide": "docs/developer-security/dependency-management-guide.md",
        "threat_ids": ["THR-SUPPLY-001", "THR-SUPPLY-002"],
        "security_requirement_ids": ["SR-SUPPLY-001", "SR-SUPPLY-002", "SR-DEV-004"],
        "control_ids": ["SR-SUPPLY-001", "SR-SUPPLY-002", "SR-DEV-004"],
        "make_targets": ["dependency-audit", "sbom", "verify-sbom", "findings-full"],
        "tests": ["tests/security/test_appsec_pipeline.py"],
        "evidence_outputs": [
            "outputs/security/appsec/dependency-scan-summary.json",
            "outputs/security/appsec/sbom.cdx.json",
        ],
        "reports": [
            "reports/security/dependency-security-report.md",
            "reports/security/sbom-report.md",
        ],
    },
    {
        "guidance_id": "DEV-GUIDE-TERRAFORM",
        "guide": "docs/developer-security/terraform-security-guide.md",
        "threat_ids": ["THR-IAC-001", "THR-IAM-001"],
        "security_requirement_ids": ["SR-IAC-001", "SR-IAC-002", "SR-IAM-001"],
        "control_ids": ["SR-IAC-001", "SR-IAC-002", "SR-IAM-001"],
        "make_targets": [
            "terraform-fmt-check",
            "terraform-validate",
            "terraform-test",
            "checkov-scan",
        ],
        "tests": ["infrastructure/tests"],
        "evidence_outputs": ["outputs/security/appsec/iac-scan-summary.json"],
        "reports": ["reports/security/terraform-security-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-CONTAINER",
        "guide": "docs/developer-security/container-security-guide.md",
        "threat_ids": ["THR-CONTAINER-001", "THR-CONTAINER-002"],
        "security_requirement_ids": ["SR-CONTAINER-001", "SR-CONTAINER-002"],
        "control_ids": ["SR-CONTAINER-001", "SR-CONTAINER-002"],
        "make_targets": ["container-build-security", "container-scan"],
        "tests": ["tests/security/test_appsec_pipeline.py"],
        "evidence_outputs": ["outputs/security/appsec/container-scan-summary.json"],
        "reports": ["reports/security/container-security-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-TRIAGE",
        "guide": "docs/developer-security/vulnerability-triage-guide.md",
        "threat_ids": ["THR-REVIEW-001", "THR-SUPPLY-001"],
        "security_requirement_ids": ["SR-FINDINGS-003", "SR-LIFECYCLE-001", "SR-LIFECYCLE-003"],
        "control_ids": ["SR-FINDINGS-003", "SR-LIFECYCLE-001", "SR-LIFECYCLE-003"],
        "make_targets": ["findings-full", "lifecycle-full"],
        "tests": [
            "tests/security/test_findings_pipeline.py",
            "tests/security/test_lifecycle_governance.py",
        ],
        "evidence_outputs": [
            "outputs/security/findings/deduplicated-findings.json",
            "outputs/security/lifecycle/vulnerability-register.json",
        ],
        "reports": ["reports/security/vulnerability-remediation-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-EXCEPTION",
        "guide": "docs/developer-security/security-exception-guide.md",
        "threat_ids": ["THR-REVIEW-001"],
        "security_requirement_ids": ["SR-LIFECYCLE-003", "SR-LIFECYCLE-004"],
        "control_ids": ["SR-LIFECYCLE-003", "SR-LIFECYCLE-004"],
        "make_targets": ["lifecycle-full", "release-full"],
        "tests": ["tests/security/test_lifecycle_governance.py"],
        "evidence_outputs": ["outputs/security/lifecycle/security-exceptions.json"],
        "reports": ["reports/security/security-exception-report.md"],
    },
    {
        "guidance_id": "DEV-GUIDE-EVIDENCE",
        "guide": "docs/developer-security/remediation-verification-guide.md",
        "threat_ids": ["THR-AUDIT-003", "THR-REVIEW-001"],
        "security_requirement_ids": ["SR-EVIDENCE-001", "SR-EVIDENCE-002", "SR-DEV-004"],
        "control_ids": ["SR-EVIDENCE-001", "SR-EVIDENCE-002", "SR-DEV-004"],
        "make_targets": ["evidence-full", "security-assurance-full"],
        "tests": ["tests/security/test_consolidated_evidence.py"],
        "evidence_outputs": ["outputs/security/evidence/evidence-manifest.json"],
        "reports": ["reports/security/security-evidence-report.md"],
    },
]


PR_CHECKLIST_ITEMS = [
    "threat-model impact",
    "authentication changes",
    "authorisation changes",
    "object-level access",
    "input validation",
    "logging",
    "secret handling",
    "dependency changes",
    "Terraform changes",
    "Docker changes",
    "new endpoints",
    "new data flows",
    "new external dependencies",
    "new suppressions",
    "new exceptions",
    "evidence regeneration",
    "release-gate impact",
]
